"""HTML report generator — produces a self-contained, single-file report.html.

Spec (section 11.2):
  - Header: topic, outcome, attempts used, total cost, wall clock
  - Rubric matrix: rows = checkpoints, columns = attempts, colour-coded PASS/FAIL
    with evidence quote on hover
  - Diff view between attempts (word-level, using difflib)
  - Cost breakdown per node
  - Guardrails that were active for this run
  - Single self-contained file (all CSS + JS inline, no external dependencies)
"""

from __future__ import annotations

import difflib
import html
import re
from datetime import UTC, datetime
from pathlib import Path

from lessonforge.state import CheckResult, RunState

# ── Ordered checkpoint list (spec Section 4) ──────────────────────────────────

CHECKPOINT_ORDER = [
    "ACC-01", "ACC-02", "ACC-03", "ACC-04",
    "LNG-01", "LNG-02", "LNG-03", "LNG-04",
    "EXM-01", "EXM-02", "EXM-03", "EXM-04",
    "COV-01", "COV-02", "COV-03", "COV-04",
    "FLW-01", "FLW-02", "FLW-03",
    "PRB-01",
]


def render_html_report(state: RunState, run_dir: Path) -> Path:
    """Render and write report.html. Returns the path."""
    out_path = run_dir / "report.html"
    html_content = _build_html(state)
    out_path.write_text(html_content, encoding="utf-8")
    return out_path


# ── HTML builder ──────────────────────────────────────────────────────────────

def _build_html(state: RunState) -> str:
    verdict = state.verdict
    ship = verdict.ship_decision if verdict else "UNKNOWN"
    attempts_used = state.attempt
    topic = html.escape(state.topic)

    outcome_color = {
        "SHIP": "#22c55e",
        "ESCALATE": "#ef4444",
        "RETRY": "#f59e0b",
        "UNKNOWN": "#94a3b8",
    }.get(ship, "#94a3b8")

    outcome_label = {
        "SHIP": "✓ SHIPPED",
        "ESCALATE": "✗ ESCALATED (needs review)",
        "RETRY": "⟳ RETRYING",
    }.get(ship, ship)

    # Gather all check results
    checks_by_id: dict[str, CheckResult] = {}
    if verdict:
        for r in verdict.all_results:
            checks_by_id[r.check_id] = r

    rubric_html = _build_rubric_matrix(checks_by_id)
    diff_html = _build_diff_section(state)
    guardrails_html = _build_guardrails_section(state.guardrails)
    metrics_html = _build_metrics_section(state)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LessonForge Report — {topic}</title>
  <style>
    {_css()}
  </style>
</head>
<body>
  <div class="container">

    <!-- Header -->
    <header>
      <div class="logo">⚡ LessonForge</div>
      <h1>{topic}</h1>
      <div class="meta-row">
        <span class="badge" style="background:{outcome_color}">{outcome_label}</span>
        <span class="meta-item">🔁 {attempts_used} attempt{"s" if attempts_used != 1 else ""}</span>
        <span class="meta-item">🆔 {html.escape(state.run_id)}</span>
        <span class="meta-item">🕐 {html.escape(state.started_at.strftime("%Y-%m-%d %H:%M UTC"))}</span>
      </div>
    </header>

    <!-- Metrics strip -->
    {metrics_html}

    <!-- Rubric Matrix -->
    <section class="card">
      <h2>📋 Rubric Matrix</h2>
      <p class="hint">Hover over <span class="fail-chip">FAIL</span> cells to see the evidence quote and repair instruction.</p>
      {rubric_html}
    </section>

    <!-- Diff view -->
    {diff_html}

    <!-- Active guardrails -->
    {guardrails_html}

    <!-- Footer -->
    <footer>
      Generated by LessonForge • {datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")}
    </footer>
  </div>
  <script>
    {_js()}
  </script>
</body>
</html>"""


# ── Section builders ──────────────────────────────────────────────────────────

def _build_rubric_matrix(checks_by_id: dict[str, CheckResult]) -> str:
    """Build the colour-coded rubric table."""
    rows = []
    dimension_colors = {
        "ACC": "#3b82f6",
        "LNG": "#8b5cf6",
        "EXM": "#f59e0b",
        "COV": "#10b981",
        "FLW": "#06b6d4",
        "PRB": "#ec4899",
    }

    current_dim = ""
    for check_id in CHECKPOINT_ORDER:
        dim = check_id[:3]
        dim_color = dimension_colors.get(dim, "#6b7280")

        # Dimension row separator
        if dim != current_dim:
            dim_labels = {
                "ACC": "🔍 Accuracy & Grounding",
                "LNG": "📖 Language & Clarity",
                "EXM": "💡 Pedagogy & Examples",
                "COV": "📚 Coverage",
                "FLW": "📐 Flow & Structure",
                "PRB": "🧠 Comprehension Probe",
            }
            rows.append(
                f'<tr class="dim-header">'
                f'<td colspan="4" style="border-left:4px solid {dim_color}">'
                f'{dim_labels.get(dim, dim)}</td></tr>'
            )
            current_dim = dim

        result = checks_by_id.get(check_id)
        if result:
            v = result.verdict
            cell_class = "pass-chip" if v == "PASS" else "fail-chip"
            severity_badge = (
                '<span class="severity hard">hard</span>'
                if result.severity == "hard"
                else '<span class="severity advisory">advisory</span>'
            )
            tooltip_content = ""
            if v == "FAIL":
                eq = html.escape(result.evidence_quote or "—")
                ri = html.escape(result.repair_instruction or "—")
                tooltip_content = f'data-tip="{eq} | Repair: {ri}"'
            judged_by = html.escape(result.judged_by or "—")
            rows.append(
                f'<tr>'
                f'<td class="check-id" style="color:{dim_color}">{check_id}</td>'
                f'<td>{html.escape(result.reason[:80])}{"…" if len(result.reason) > 80 else ""}</td>'
                f'<td>{severity_badge}</td>'
                f'<td><span class="{cell_class}" {tooltip_content}>{v}</span>'
                f'<div class="judged-by">{judged_by}</div></td>'
                f'</tr>'
            )
        else:
            rows.append(
                f'<tr>'
                f'<td class="check-id" style="color:{dim_color}">{check_id}</td>'
                f'<td colspan="3" class="not-run">— not evaluated</td>'
                f'</tr>'
            )

    rows_html = "\n".join(rows)
    return f"""<table class="rubric-table">
  <thead>
    <tr>
      <th>Check ID</th>
      <th>Reason</th>
      <th>Severity</th>
      <th>Verdict</th>
    </tr>
  </thead>
  <tbody>
    {rows_html}
  </tbody>
</table>"""


def _build_diff_section(state: RunState) -> str:
    """Word-level diff between lesson attempts using difflib."""
    lessons = list(state.lesson_history)
    if state.lesson and state.lesson not in lessons:
        lessons.append(state.lesson)

    if len(lessons) < 2:
        return ""

    diff_cards = []
    for i in range(len(lessons) - 1):
        a_md = lessons[i].to_markdown()
        b_md = lessons[i + 1].to_markdown()
        diff_html = _word_diff_html(a_md, b_md)
        diff_cards.append(
            f'<div class="diff-pair">'
            f'<h3>Attempt {i + 1} → Attempt {i + 2}</h3>'
            f'<div class="diff-view">{diff_html}</div>'
            f'</div>'
        )

    return f"""<section class="card">
  <h2>🔀 Diff Between Attempts</h2>
  {"".join(diff_cards)}
</section>"""


def _word_diff_html(a: str, b: str) -> str:
    """Produce word-level HTML diff."""
    a_words = re.split(r"(\s+)", a)
    b_words = re.split(r"(\s+)", b)
    sm = difflib.SequenceMatcher(None, a_words, b_words, autojunk=False)
    parts = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            parts.append(html.escape("".join(a_words[i1:i2])))
        elif tag == "replace":
            parts.append(f'<del>{"".join(html.escape(w) for w in a_words[i1:i2])}</del>')
            parts.append(f'<ins>{"".join(html.escape(w) for w in b_words[j1:j2])}</ins>')
        elif tag == "delete":
            parts.append(f'<del>{"".join(html.escape(w) for w in a_words[i1:i2])}</del>')
        elif tag == "insert":
            parts.append(f'<ins>{"".join(html.escape(w) for w in b_words[j1:j2])}</ins>')
    return "".join(parts)


def _build_guardrails_section(guardrails: list[str]) -> str:
    if not guardrails:
        return ""
    items = "".join(
        f'<li class="guardrail-item">🛡 {html.escape(g)}</li>'
        for g in guardrails
    )
    return f"""<section class="card">
  <h2>🛡 Active Guardrails (injected from memory)</h2>
  <ul class="guardrail-list">{items}</ul>
</section>"""


def _build_metrics_section(state: RunState) -> str:
    metrics = state.structural_report.metrics if state.structural_report else {}
    wc = int(metrics.get("word_count", 0))
    fk = float(metrics.get("fk_grade", 0.0))
    jh = int(metrics.get("jargon_hits", 0))
    verdict = state.verdict.ship_decision if state.verdict else "UNKNOWN"
    hard_fails = len(state.verdict.hard_fails) if state.verdict else 0

    verdict_color = {"SHIP": "#22c55e", "ESCALATE": "#ef4444"}.get(verdict, "#f59e0b")

    return f"""<div class="metrics-strip">
  <div class="metric"><span class="metric-val">{wc}</span><span class="metric-label">words</span></div>
  <div class="metric"><span class="metric-val">{fk:.1f}</span><span class="metric-label">FK grade</span></div>
  <div class="metric"><span class="metric-val">{jh}</span><span class="metric-label">jargon hits</span></div>
  <div class="metric"><span class="metric-val" style="color:{verdict_color}">{hard_fails}</span><span class="metric-label">hard fails</span></div>
</div>"""


# ── CSS and JS ────────────────────────────────────────────────────────────────

def _css() -> str:
    return """
    :root {
      --bg: #0f172a;
      --surface: #1e293b;
      --surface2: #253149;
      --border: #334155;
      --text: #e2e8f0;
      --text-dim: #94a3b8;
      --pass: #22c55e;
      --fail: #ef4444;
      --advisory: #f59e0b;
      --accent: #6366f1;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      padding: 0 0 3rem;
    }
    .container { max-width: 1100px; margin: 0 auto; padding: 0 1.5rem; }

    header {
      background: linear-gradient(135deg, #1e1b4b 0%, #0f172a 60%);
      border-bottom: 1px solid var(--border);
      padding: 2rem 1.5rem 1.5rem;
      margin-bottom: 1.5rem;
    }
    .logo { font-size: 0.875rem; font-weight: 700; color: var(--accent); letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 0.5rem; }
    header h1 { font-size: 1.75rem; font-weight: 800; color: #f1f5f9; margin-bottom: 1rem; }
    .meta-row { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: center; }
    .badge { padding: 0.3rem 0.9rem; border-radius: 9999px; font-size: 0.8rem; font-weight: 700; color: white; }
    .meta-item { font-size: 0.8rem; color: var(--text-dim); }

    .metrics-strip {
      display: flex; gap: 1rem; flex-wrap: wrap;
      background: var(--surface); border: 1px solid var(--border);
      border-radius: 12px; padding: 1.25rem 1.5rem; margin-bottom: 1.5rem;
    }
    .metric { flex: 1; min-width: 100px; text-align: center; }
    .metric-val { display: block; font-size: 2rem; font-weight: 800; color: var(--text); }
    .metric-label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-dim); }

    .card {
      background: var(--surface); border: 1px solid var(--border);
      border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem;
    }
    .card h2 { font-size: 1.1rem; font-weight: 700; margin-bottom: 1rem; color: #f1f5f9; }
    .hint { font-size: 0.8rem; color: var(--text-dim); margin-bottom: 0.75rem; }

    .rubric-table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    .rubric-table th {
      background: var(--surface2); color: var(--text-dim);
      font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;
      padding: 0.6rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border);
    }
    .rubric-table td { padding: 0.55rem 0.75rem; border-bottom: 1px solid var(--border); vertical-align: middle; }
    .rubric-table tr:hover td { background: rgba(255,255,255,0.03); }
    .dim-header td {
      font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
      letter-spacing: 0.06em; color: var(--text-dim);
      background: rgba(0,0,0,0.2); padding: 0.5rem 0.75rem;
    }
    .check-id { font-family: monospace; font-weight: 700; font-size: 0.85rem; white-space: nowrap; }
    .not-run { color: var(--text-dim); font-style: italic; }

    .pass-chip, .fail-chip {
      display: inline-block; padding: 0.2rem 0.6rem;
      border-radius: 9999px; font-size: 0.75rem; font-weight: 700;
      cursor: default;
    }
    .pass-chip { background: rgba(34,197,94,0.15); color: var(--pass); border: 1px solid rgba(34,197,94,0.3); }
    .fail-chip { background: rgba(239,68,68,0.15); color: var(--fail); border: 1px solid rgba(239,68,68,0.3); cursor: help; }
    .fail-chip:hover { background: rgba(239,68,68,0.25); }

    .severity { font-size: 0.7rem; padding: 0.15rem 0.45rem; border-radius: 4px; }
    .severity.hard { background: rgba(239,68,68,0.1); color: #fca5a5; border: 1px solid rgba(239,68,68,0.2); }
    .severity.advisory { background: rgba(245,158,11,0.1); color: #fde68a; border: 1px solid rgba(245,158,11,0.2); }
    .judged-by { font-size: 0.65rem; color: var(--text-dim); margin-top: 2px; }

    /* Tooltip */
    [data-tip] { position: relative; }
    [data-tip]:hover::after {
      content: attr(data-tip);
      position: absolute; right: 0; top: calc(100% + 6px);
      background: #1e293b; border: 1px solid #ef4444;
      color: #fecaca; font-size: 0.75rem; padding: 0.6rem 0.8rem;
      border-radius: 8px; max-width: 340px; z-index: 999;
      white-space: pre-wrap; line-height: 1.5; font-weight: 400;
      box-shadow: 0 8px 24px rgba(0,0,0,0.5);
    }

    /* Diff */
    .diff-pair { margin-bottom: 1.5rem; }
    .diff-pair h3 { font-size: 0.9rem; color: var(--text-dim); margin-bottom: 0.5rem; font-weight: 600; }
    .diff-view {
      background: #0d1b2a; border: 1px solid var(--border); border-radius: 8px;
      padding: 1rem; font-family: monospace; font-size: 0.78rem;
      line-height: 1.7; max-height: 400px; overflow-y: auto;
      white-space: pre-wrap; word-break: break-word; color: var(--text);
    }
    ins { background: rgba(34,197,94,0.2); color: #86efac; text-decoration: none; }
    del { background: rgba(239,68,68,0.2); color: #fca5a5; text-decoration: line-through; }

    /* Guardrails */
    .guardrail-list { list-style: none; display: flex; flex-direction: column; gap: 0.5rem; }
    .guardrail-item {
      background: rgba(99,102,241,0.1); border: 1px solid rgba(99,102,241,0.2);
      border-radius: 8px; padding: 0.6rem 0.9rem; font-size: 0.85rem; color: #c7d2fe;
    }

    footer { text-align: center; color: var(--text-dim); font-size: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }
    """


def _js() -> str:
    return ""  # Pure CSS tooltips — no JS needed
